apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: landing_page
  name: landing_page
spec:
  replicas: 3
  selector:
    matchLabels:
      app: landing_page
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: landing_page
    spec:
      containers:
      - image: kstubh/landing-page:3
        name: landing_page
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: landing_page
